name: Unit Test
on:
  pull_request:
    paths:
      - server.go
      - vendor/handler/*
      - .github/workflows/server_unit.yml
  push:
    branches:
      - main
    paths:
      - server.go
      - vendor/handler/*
      - .github/workflows/server_unit.yml
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Wait for DB to be ready
        run: |
          docker compose up -d
          until docker compose exec -T redis redis-cli ping; do
            echo 'Waiting for DB to be ready...'
            sleep 1
          done
      - name: Unit Test
        run: |
          go test -v
